/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Ven1_FormularioBuscar extends javax.swing.JFrame {

    /**
     * Creates new form Ven2_FormularioBuscar
     */
    public Ven1_FormularioBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBIEN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCTIPOINMUEBLE = new javax.swing.JComboBox<>();
        jCTipoOper = new javax.swing.JComboBox<>();
        jCNHab = new javax.swing.JComboBox<>();
        jCCiudad = new javax.swing.JComboBox<>();
        jBBUSCAR = new javax.swing.JButton();
        jLINFORMACION = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jBCONTACTO = new javax.swing.JButton();
        jPMANTENIMIENTO = new javax.swing.JPanel();
        jBMANTENIMIENTO = new javax.swing.JButton();
        jLSOLOADMIN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBIEN.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("BIENVENIDOS");

        javax.swing.GroupLayout jBIENLayout = new javax.swing.GroupLayout(jBIEN);
        jBIEN.setLayout(jBIENLayout);
        jBIENLayout.setHorizontalGroup(
            jBIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBIENLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jBIENLayout.setVerticalGroup(
            jBIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBIENLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jBIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 910, 110));

        jCTIPOINMUEBLE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTIPOINMUEBLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO INMUEBLE", "CASA", "DEPARTAMENTO", "TERRENO" }));
        jCTIPOINMUEBLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTIPOINMUEBLEActionPerformed(evt);
            }
        });
        getContentPane().add(jCTIPOINMUEBLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 168, 230, 30));

        jCTipoOper.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTipoOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE OPERACION", "VENTA", "ALQUILER", "TEMPORADA", "TRASPASO" }));
        jCTipoOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoOperActionPerformed(evt);
            }
        });
        getContentPane().add(jCTipoOper, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jCNHab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCNHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N° DE HABITACIONES", "1", "2", "3", "4", "5" }));
        getContentPane().add(jCNHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jCCiudad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIUDAD", "Arequipa", "Trujillo", "Chiclayo", "Lima", "Piura" }));
        getContentPane().add(jCCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jBBUSCAR.setBackground(new java.awt.Color(0, 102, 102));
        jBBUSCAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBBUSCAR.setForeground(new java.awt.Color(0, 102, 102));
        jBBUSCAR.setText("BUSCAR");
        jBBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(jBBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 140, 60));

        jLINFORMACION.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLINFORMACION.setText("INFORMACION");
        jLINFORMACION.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLINFORMACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));
        getContentPane().add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 50, 30));

        jBCONTACTO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBCONTACTO.setForeground(new java.awt.Color(0, 102, 102));
        jBCONTACTO.setText("CONTACTO");
        jBCONTACTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCONTACTOActionPerformed(evt);
            }
        });
        getContentPane().add(jBCONTACTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jBMANTENIMIENTO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBMANTENIMIENTO.setText("MANTENIMIENTO");
        jBMANTENIMIENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMANTENIMIENTOActionPerformed(evt);
            }
        });

        jLSOLOADMIN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSOLOADMIN.setText("SOLO ADMINISTRADORES");

        javax.swing.GroupLayout jPMANTENIMIENTOLayout = new javax.swing.GroupLayout(jPMANTENIMIENTO);
        jPMANTENIMIENTO.setLayout(jPMANTENIMIENTOLayout);
        jPMANTENIMIENTOLayout.setHorizontalGroup(
            jPMANTENIMIENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMANTENIMIENTOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSOLOADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPMANTENIMIENTOLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBMANTENIMIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPMANTENIMIENTOLayout.setVerticalGroup(
            jPMANTENIMIENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMANTENIMIENTOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLSOLOADMIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBMANTENIMIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPMANTENIMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 810, 170));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/fondotodo.png"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBUSCARActionPerformed
        // TODO add your handling code here:
       // int tm1 = jCTIPOINMUEBLE.getSelectedIndex();
   String tm = "";
   String to ="";
   String ciu ="";
   int nh=0;
   String snh;
   
    
  if(jCTIPOINMUEBLE.getSelectedIndex() > 0){
      tm = (String) jCTIPOINMUEBLE.getSelectedItem();  
  }
  if(jCTipoOper.getSelectedIndex() > 0){
      to = (String) jCTipoOper.getSelectedItem();
  }
  
  if(jCCiudad.getSelectedIndex() > 0){
      ciu= (String) jCCiudad.getSelectedItem();
  }
  
  if(jCNHab.getSelectedIndex() > 0) //!=
  {
   nh=(int)jCNHab.getSelectedItem();
    snh=(String)jCNHab.getSelectedItem();
  }
  
       
        JOptionPane.showMessageDialog(null,tm);
    }//GEN-LAST:event_jBBUSCARActionPerformed

    private void jBCONTACTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCONTACTOActionPerformed
        // TODO add your handling code here:
        Ven3_FormularioInforInmueble ven3= new Ven3_FormularioInforInmueble();
        ven3.setVisible(true);
    }//GEN-LAST:event_jBCONTACTOActionPerformed

    private void jBMANTENIMIENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMANTENIMIENTOActionPerformed

        Ven2_IngresoAdminManten ven2= new Ven2_IngresoAdminManten();
        ven2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jBMANTENIMIENTOActionPerformed

    private void jCTipoOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoOperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoOperActionPerformed

    private void jCTIPOINMUEBLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTIPOINMUEBLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTIPOINMUEBLEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ven1_FormularioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ven1_FormularioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ven1_FormularioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ven1_FormularioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ven1_FormularioBuscar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBUSCAR;
    private javax.swing.JButton jBCONTACTO;
    private javax.swing.JPanel jBIEN;
    private javax.swing.JButton jBMANTENIMIENTO;
    private javax.swing.JComboBox<String> jCCiudad;
    private javax.swing.JComboBox<String> jCNHab;
    private javax.swing.JComboBox<String> jCTIPOINMUEBLE;
    private javax.swing.JComboBox<String> jCTipoOper;
    private javax.swing.JLabel jLINFORMACION;
    private javax.swing.JLabel jLSOLOADMIN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPMANTENIMIENTO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
