/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

/**
 *
 * @author Alma Valer Vilca
 */
public class Ven4_FormularioMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form Ven4_FormularioMantenimiento
     */
    public Ven4_FormularioMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCTIPOINMUEBLE = new javax.swing.JComboBox<>();
        jCCiudad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBINSERTAR = new javax.swing.JButton();
        jBMODIFICAR = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("MANTENIMIENTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("TIPO DE INMUEBLE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jCTIPOINMUEBLE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCTIPOINMUEBLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELEGIR", "CASA", "DEPARTAMENTO", "TERRENO" }));
        jCTIPOINMUEBLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTIPOINMUEBLEActionPerformed(evt);
            }
        });
        getContentPane().add(jCTIPOINMUEBLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jCCiudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIUDAD", "Arequipa", "Trujillo", "Chiclayo", "Lima", "Piura" }));
        getContentPane().add(jCCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CODIGO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 40, 20));

        jBINSERTAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBINSERTAR.setForeground(new java.awt.Color(0, 102, 102));
        jBINSERTAR.setText("INSERTAR");
        jBINSERTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBINSERTARActionPerformed(evt);
            }
        });
        getContentPane().add(jBINSERTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jBMODIFICAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMODIFICAR.setForeground(new java.awt.Color(0, 102, 102));
        jBMODIFICAR.setText("MODIFICAR");
        jBMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(jBMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/triple.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 400, 140));

        jLFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/fondotodo.png"))); // NOI18N
        getContentPane().add(jLFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCTIPOINMUEBLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTIPOINMUEBLEActionPerformed
        // TODO add your handling code here:
        
       String ti= "";
       String ciu= " ";
       
       if(jCTIPOINMUEBLE.getSelectedIndex() > 0){ 
       ti = (String) jCTIPOINMUEBLE.getSelectedItem();
       }
       
       if(jCCiudad.getSelectedIndex() > 0){
       ciu= (String) jCCiudad.getSelectedItem();
       }
           
       
    
    }//GEN-LAST:event_jCTIPOINMUEBLEActionPerformed

    private void jBINSERTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBINSERTARActionPerformed
        // TODO add your handling code here:
        Ven5_Insertar ven5 = new Ven5_Insertar();
        ven5.setVisible(true);

    }//GEN-LAST:event_jBINSERTARActionPerformed

    private void jBMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMODIFICARActionPerformed
        // TODO add your handling code here:
        Ven6_Modificar ven6 = new Ven6_Modificar();
        ven6.setVisible(true);

    }//GEN-LAST:event_jBMODIFICARActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ven4_FormularioMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ven4_FormularioMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ven4_FormularioMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ven4_FormularioMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ven4_FormularioMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBINSERTAR;
    private javax.swing.JButton jBMODIFICAR;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCCiudad;
    private javax.swing.JComboBox<String> jCTIPOINMUEBLE;
    private javax.swing.JLabel jLFONDO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
